---
title: "elevatr"
author: "Tao"
date:  "`r Sys.Date()`"
output: html_document
---

```{r}
#The R package elevatr is used to access elevation data.
#install.packages("elevatr")
#install.packages('rgdal')
library("rgdal")
library("elevatr")
library("raster")
library("foreign")
```

```{r}
#wt<-read.dbf("C:/Users/taohuang/Documents/Tao/Data/norwest/usgs_wt_ID.dbf")

wt <- readOGR("C:/Users/taohuang/Documents/Tao/Data/norwest/usgs_wt_ID.shp")
#wt$x<-wt$LNG_GAGE
#wt$y<-wt$LNG_GAGE
#wt<-wt[,c("x","y")]
wt
```

```{r}
wt_ele <- get_elev_raster(locations =wt, z = 14)

wt_ele

```

#USGS gauge number
```{r}
stn<- 14362250
```

#read study area
```{r}
#my_spdf <- readOGR(   dsn=  paste("C:/Users/taohuang/Documents/Tao/Data/",stn,"/download(4)/layers",sep="")  , 
#  layer="globalwatershed")

my_spdf <- readOGR( 
  dsn=  paste("C:/Users/taohuang/Desktop/layers",sep="")  , 
  layer="globalwatershed"
)

my_spdf

```

```{r}
usgs <- get_elev_raster(my_spdf, z = 14)
usgs 

writeRaster(usgs , paste("C:/Users/taohuang/Desktop/layers/usgs_dem.tif",sep=""), format="GTiff", overwrite=TRUE)

#writeRaster(usgs , paste("C:/Users/taohuang/Documents/Tao/Data/",stn, "/usgs_dem.tif",sep=""), format="GTiff", overwrite=TRUE)
  
```

